version: '3.8'

services:
  nodeapp:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"  # Map port 3000 on host to port 3000 in the container
    volumes:
      - .:/usr/src/index  # Optional: Mount the current directory to the container for live updates
    restart: always  # Automatically restart the container on failure